# Generated by Django 5.1.7 on 2025-03-11 19:36

import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatorEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('code', encrypted_model_fields.fields.EncryptedCharField(verbose_name='fingerprint code')),
                ('pfp', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='profile picture')),
                ('title', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('punched_in', models.BooleanField(default=False)),
                ('_prev_punch_state', models.BooleanField(default=False)),
                ('_prev_fingerprint_code', encrypted_model_fields.fields.EncryptedCharField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
        migrations.CreateModel(
            name='AuthenticatorLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('punch_in', 'Punched in'), ('punch_out', 'Punched out'), ('assign_code', 'Assigned fingerprint code'), ('created', 'Created'), ('unknown', 'Unknown action')], default='unknown', max_length=1024)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terminusgps_authenticator.authenticatoremployee')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
            },
        ),
        migrations.CreateModel(
            name='AuthenticatorLogReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('logs', models.ManyToManyField(to='terminusgps_authenticator.authenticatorlogitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
            },
        ),
        migrations.CreateModel(
            name='AuthenticatorEmployeeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, default=None, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminusgps_authenticator.authenticatoremployee')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='terminusgps_authenticator.authenticatorlogreport')),
            ],
            options={
                'verbose_name': 'shift',
                'verbose_name_plural': 'shifts',
            },
        ),
    ]
