# Generated by Django 5.1.6 on 2025-02-27 16:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticatorEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('code', models.CharField(max_length=2048, verbose_name='fingerprint code')),
                ('slug', models.SlugField(blank=True, default=None, null=True)),
                ('pstate', models.CharField(choices=[('in', 'Punch in'), ('out', 'Punch out')], default='in', max_length=3, verbose_name='punch state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
        migrations.CreateModel(
            name='AuthenticatorLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('pstate', models.CharField(choices=[('in', 'Punch in'), ('out', 'Punch out')], max_length=3, verbose_name='punch state')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terminusgps_authenticator.authenticatoremployee')),
            ],
            options={
                'verbose_name': 'log item',
                'verbose_name_plural': 'log items',
            },
        ),
    ]
