# Generated by Django 5.1.6 on 2025-02-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_authenticator', '0002_alter_authenticatoremployee_punched_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatorlogitem',
            name='action',
            field=models.CharField(choices=[('punch_in', 'Punch-in'), ('punch_out', 'Punch-out'), ('assign_code', 'Punch-out')], default='punch_in', max_length=1024),
        ),
    ]
