# Generated by Django 5.1.7 on 2025-03-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_authenticator', '0002_authenticatoremployee_pfp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authenticatoremployee',
            name='_punched_in',
        ),
        migrations.AddField(
            model_name='authenticatoremployee',
            name='_prev_punch_state',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='authenticatoremployee',
            name='punched_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='authenticatorlogitem',
            name='action',
            field=models.CharField(choices=[('punch_in', 'Punched in'), ('punch_out', 'Punched out'), ('assign_code', 'Assigned fingerprint code'), ('created', 'Created'), ('unknown', 'Unknown action')], default='unknown', max_length=1024),
        ),
    ]
