# Generated by Django 5.1.7 on 2025-03-07 17:05

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_authenticator', '0003_remove_authenticatoremployee__punched_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatoremployee',
            name='_prev_fingerprint_code',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='authenticatorlogitem',
            name='action',
            field=models.CharField(choices=[('punch_in', 'Punched in'), ('punch_out', 'Punched out'), ('assign_code', 'Assigned fingerprint code'), ('unknown', 'Unknown action')], default='unknown', max_length=1024),
        ),
    ]
