# Generated by Django 5.1.6 on 2025-02-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_authenticator', '0003_alter_authenticatorlogitem_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatorlogitem',
            name='action',
            field=models.CharField(choices=[('punch_in', 'Punched in'), ('punch_out', 'Punched out'), ('assign_code', 'Assigned fingerprint code')], default='punch_in', max_length=1024),
        ),
    ]
