# Generated by Django 5.1.7 on 2025-03-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_authenticator', '0004_authenticatoremployee__prev_fingerprint_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenticatorlogitem',
            options={'verbose_name': 'log', 'verbose_name_plural': 'logs'},
        ),
        migrations.AlterModelOptions(
            name='authenticatorlogreport',
            options={'verbose_name': 'report', 'verbose_name_plural': 'reports'},
        ),
        migrations.AddField(
            model_name='authenticatorlogreport',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='authenticatorlogitem',
            name='action',
            field=models.CharField(choices=[('punch_in', 'Punched in'), ('punch_out', 'Punched out'), ('assign_code', 'Assigned fingerprint code'), ('created', 'Created'), ('unknown', 'Unknown action')], default='unknown', max_length=1024),
        ),
    ]
