# Generated by Django 5.1.7 on 2025-03-07 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_authenticator', '0005_alter_authenticatorlogitem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticatorlogreport',
            old_name='items',
            new_name='logs',
        ),
        migrations.CreateModel(
            name='AuthenticatorEmployeeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='terminusgps_authenticator.authenticatoremployee')),
            ],
        ),
    ]
