# Generated by Django 5.1.7 on 2025-03-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_authenticator', '0006_rename_items_authenticatorlogreport_logs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticatoremployeeshift',
            name='tdelta',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
    ]
