# Generated by Django 5.1.7 on 2025-03-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminusgps_authenticator', '0007_authenticatoremployeeshift_tdelta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenticatoremployeeshift',
            options={'verbose_name': 'shift', 'verbose_name_plural': 'shifts'},
        ),
        migrations.RenameField(
            model_name='authenticatoremployeeshift',
            old_name='tdelta',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='authenticatorlogreport',
            old_name='file',
            new_name='pdf',
        ),
        migrations.AddField(
            model_name='authenticatoremployee',
            name='shifts',
            field=models.ManyToManyField(to='terminusgps_authenticator.authenticatoremployeeshift'),
        ),
        migrations.AddField(
            model_name='authenticatorlogreport',
            name='shifts',
            field=models.ManyToManyField(blank=True, default=None, to='terminusgps_authenticator.authenticatoremployeeshift'),
        ),
    ]
